# Generated by Django 3.1.5 on 2021-02-02 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_entry_bg_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='bg_image',
            field=models.ImageField(upload_to='blogs_images'),
        ),
    ]
